remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: NossoZap Documentation
description: Documentação técnica do NossoZap - Sistema de chat em tempo real
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/joao-bolsoni/NossoZap-docs 